### ISSUE TITLE
rendering error when inserting a datePicker inside a modal

### ISSUE THREAD

**Issue by juliotnu01** [themesberg/flowbite#158]
when a datePicker is inserted into a modal, and clicked to select the date, the date display is overlapped by the modal container

![image](https://user-images.githubusercontent.com/15963809/169721597-62ab7b6a-4344-48b4-9eab-27d4cae665f9.png)

**Comment by zoltanszogyenyi** [comment]
Hey @juliotnu01,

Thanks for the reporting, this will be solved by adding a larger `z-index` to the datepicker.

**Comment by chas688** [comment]
I have this issue as well and am adding a z-50 (Tailwind CSS) to the input. However, it is not getting picked up and the default is going back to z-20 on the modal itself.

**Comment by zoltanszogyenyi** [comment]
@juliotnu01 @chas688 This has been fixed via the v1.5.0 update.

**Comment by allestaire** [comment]
This issue not yet resolve

<img width="320" alt="Screen Shot 2023-12-11 at 2 32 05 PM" src="https://github.com/themesberg/flowbite/assets/68372409/ded94bbd-60e3-44db-8f5e-3b113c167a37">

**Comment by mtthidoteu** [comment]
> This issue not yet resolve
> 
> <img alt="Screen Shot 2023-12-11 at 2 32 05 PM" width="320" src="https://private-user-images.githubusercontent.com/68372409/289445075-ded94bbd-60e3-44db-8f5e-3b113c167a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjY5NzEsIm5iZiI6MTcwMjQ2NjY3MSwicGF0aCI6Ii82ODM3MjQwOS8yODk0NDUwNzUtZGVkOTRiYmQtNjBlMy00NGRiLThmNWUtM2IxMTNjMTY3YTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMmQ4OTgyNmNiNGM2NzYxNDk0NjM0OTQ2ZTdmOGJhNDYzMmU0ZWEzOWU3MTk0NjkyYjAyNjJiNjcwZjYyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NTL3ZFaz6pwn3gyGZIcvuPuRPRsET75PeTbWajH8FGE">
> But the solution above hits the right path!! 😄

I am also having this issue. How did you fix it exactly?

**Comment by allestaire** [comment]
> > This issue not yet resolve
> > <img alt="Screen Shot 2023-12-11 at 2 32 05 PM" width="320" src="https://private-user-images.githubusercontent.com/68372409/289445075-ded94bbd-60e3-44db-8f5e-3b113c167a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjY5NzEsIm5iZiI6MTcwMjQ2NjY3MSwicGF0aCI6Ii82ODM3MjQwOS8yODk0NDUwNzUtZGVkOTRiYmQtNjBlMy00NGRiLThmNWUtM2IxMTNjMTY3YTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMmQ4OTgyNmNiNGM2NzYxNDk0NjM0OTQ2ZTdmOGJhNDYzMmU0ZWEzOWU3MTk0NjkyYjAyNjJiNjcwZjYyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NTL3ZFaz6pwn3gyGZIcvuPuRPRsET75PeTbWajH8FGE">
> > But the solution above hits the right path!! 😄
> 
> I am also having this issue. How did you fix it exactly?

You have to set its parent to relative position, `positive: relative`

**Comment by philharmonie** [comment]
Still facing this issue in my component:
```vue
<template>
    <Card class="group relative select-none hover:cursor-pointer">
        <div class="relative">
            <!-- Filter -->
            <div class="absolute inset-0 z-30 flex w-full gap-2 bg-white">
                <div class="flex flex-col gap-3">
                    <div class="relative z-40 max-w-sm">
                        {{ from }}
                        <div
                            class="pointer-events-none absolute inset-y-0 start-0 flex items-center ps-3.5">
                            <svg
                                class="h-3 w-3 text-gray-500 dark:text-gray-400"
                                aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="currentColor"
                                viewBox="0 0 20 20">
                                <path
                                    d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
                            </svg>
                        </div>
                        <input
                            datepicker
                            datepicker-autohide="true"
                            datepicker-format="yyyy-mm-dd"
                            v-model="from"
                            type="text"
                            class="z-50 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2 ps-10 text-xs text-gray-900 focus:border-primary-500 focus:ring-primary-500"
                            placeholder="Select start" />
                    </div>
                    <div class="relative z-40 max-w-sm">
                        <div
                            class="pointer-events-none absolute inset-y-0 start-0 flex items-center ps-3.5">
                            <svg
                                class="h-3 w-3 text-gray-500 dark:text-gray-400"
                                aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg"
                                fill="currentColor"
                                viewBox="0 0 20 20">
                                <path
                                    d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
                            </svg>
                        </div>
                        <input
                            datepicker
                            datepicker-autohide="true"
                            datepicker-format="yyyy-mm-dd"
                            v-model="from"
                            type="text"
                            class="z-50 block w-full rounded-lg border border-gray-300 bg-gray-50 p-2 ps-10 text-xs text-gray-900 focus:border-primary-500 focus:ring-primary-500"
                            placeholder="Select end" />
                    </div>
                </div>
                <button class="btn h-full">OK</button>
            </div>
            <header class="flex items-center justify-between gap-2">
                <div class="flex items-center gap-2">
                    <CurrencyEuroIcon class="h-5 w-5 text-gray-400" />
                    <div class="text-base font-bold text-gray-600">Sales Volume</div>
                </div>
                <transition>
                    <div class="text-xs text-gray-400 group-hover:text-gray-800">Filter</div>
                </transition>
            </header>
        </div>
    </Card>
</template>
```

The picker is behind the component

**Comment by chas688** [comment]
That looks right, you may try moving the "relative" one level up in the DOM, just below the absolute position, but it does look right and the z-50 should have it pop up on top. My issue was that the CSS for the flowbyte package wasn't being properly installed with the package manager. You may want to head down that path. One way to know is that in your browser inspector tools, find the datepicker in the inspector and see if the flowbite css used is even registering.
